"""Tests for SWC loading.

SWC is whitespace-delimited but writers disagree on which whitespace: the
Allen files use a single space, while MorphIO (v3.3.3 was the version reported
in issue #8) pads its columns so runs of spaces separate the fields. Splitting
on a literal single space silently turns every padded row into NaNs rather
than raising, so the tests below check the parsed values, not just the shape.
"""

import numpy as np
import pandas as pd
import pytest

from ccf_streamlines.morphology import (
    load_swc_as_dataframe,
    transform_swc_to_volume,
)

COLUMNS = ["id", "type", "x", "y", "z", "r", "parent_id"]

# The same three nodes, written five ways.
ROWS = [
    (1, 1, 100.0, 200.0, 300.0, 5.0, -1),
    (2, 2, 110.0, 200.0, 300.0, 1.0, 1),
    (3, 3, 100.0, 215.0, 320.0, 1.5, 1),
]

SINGLE_SPACE = "\n".join(" ".join(str(v) for v in row) for row in ROWS) + "\n"

SWC_VARIANTS = {
    "single_space": SINGLE_SPACE,
    "multiple_spaces": (
        "1 1  100.0   200.0 300.0 5.0 -1\n"
        "2  2 110.0 200.0  300.0 1.0 1\n"
        "3 3 100.0  215.0 320.0   1.5 1\n"
    ),
    "tabs": "\n".join("\t".join(str(v) for v in row) for row in ROWS) + "\n",
    "aligned_columns": (
        "1 1 100.0 200.0 300.0 5.0 -1\n"
        "2 2 110.0 200.0 300.0 1.0  1\n"
        "3 3 100.0 215.0 320.0 1.5  1\n"
    ),
    "trailing_whitespace": "".join(
        " ".join(str(v) for v in row) + "   \n" for row in ROWS
    ),
}


@pytest.fixture
def expected_df():
    return pd.DataFrame(ROWS, columns=COLUMNS)


def write_swc(tmp_path, name, text, header=""):
    path = tmp_path / f"{name}.swc"
    path.write_text(header + text)
    return str(path)


@pytest.mark.parametrize("variant", sorted(SWC_VARIANTS))
def test_load_swc_handles_any_whitespace_delimiter(tmp_path, variant, expected_df):
    """Any run of whitespace separates fields, per issue #8."""
    swc_file = write_swc(tmp_path, variant, SWC_VARIANTS[variant])

    df = load_swc_as_dataframe(swc_file)

    pd.testing.assert_frame_equal(df, expected_df)


def test_load_swc_skips_comment_header(tmp_path, expected_df):
    """A ``#`` header - what MorphIO writes - is still dropped."""
    header = "# generated by MorphIO v3.3.3\n# id type x y z r parent\n"
    swc_file = write_swc(
        tmp_path, "commented", SWC_VARIANTS["multiple_spaces"], header=header
    )

    df = load_swc_as_dataframe(swc_file)

    pd.testing.assert_frame_equal(df, expected_df)


def test_load_swc_keeps_integer_columns(tmp_path):
    """The NaN-filling failure mode also floated ``id``/``type``/``parent_id``."""
    swc_file = write_swc(tmp_path, "ints", SWC_VARIANTS["multiple_spaces"])

    df = load_swc_as_dataframe(swc_file)

    for column in ("id", "type", "parent_id"):
        assert df[column].dtype.kind == "i", column
    assert not df.isna().to_numpy().any()


def test_transform_swc_to_volume_matches_across_delimiters(tmp_path):
    """The delimiter must not reach the projected volume."""
    volume_shape = (40, 40, 40)
    resolution = (10, 10, 10)

    volumes = {
        variant: transform_swc_to_volume(
            write_swc(tmp_path, variant, text),
            volume_shape=volume_shape,
            resolution=resolution,
        )
        for variant, text in SWC_VARIANTS.items()
    }

    reference = volumes["single_space"]
    assert reference.sum() == len(ROWS)
    assert reference[10, 20, 30] == 1
    for variant, volume in volumes.items():
        assert np.array_equal(volume, reference), variant
