"""Morphology loading and coordinate-to-volume transformation.

``transform_swc_to_volume`` and ``transform_coordinates_to_volume`` default to
the full CCF shape, which allocates a 1320 x 800 x 1140 array. Every call here
passes a small shape explicitly.
"""

import numpy as np
import pandas as pd
import pytest

from ccf_streamlines.morphology import (
    find_topological_point_coordinates,
    load_swc_as_dataframe,
    transform_coordinates_to_volume,
    transform_swc_to_volume,
)

ISSUE_8 = (
    "pinned to AllenInstitute/ccf_streamlines#8: load_swc_as_dataframe uses "
    "sep=' ' and cannot read the delimiters real reconstruction tools emit; "
    "remove this marker when it is fixed"
)

# id type x y z r parent_id
SPACE_DELIMITED = (
    "# generated by a reconstruction tool\n"
    "1 1 0.0 0.0 0.0 1.0 -1\n"
    "2 3 10.0 0.0 0.0 1.0 1\n"
    "3 3 20.0 0.0 0.0 1.0 2\n"
    "4 3 10.0 10.0 0.0 1.0 2\n"
)


@pytest.fixture
def swc_file(tmp_path):
    path = tmp_path / "neuron.swc"
    path.write_text(SPACE_DELIMITED)
    return str(path)


def test_space_delimited_swc_loads(swc_file):
    df = load_swc_as_dataframe(swc_file)

    assert list(df.columns) == ["id", "type", "x", "y", "z", "r", "parent_id"]
    assert len(df) == 4
    assert df["id"].tolist() == [1, 2, 3, 4]
    assert df["x"].tolist() == [0.0, 10.0, 20.0, 10.0]
    assert df["parent_id"].tolist() == [-1, 1, 2, 2]


def test_comment_lines_are_skipped(swc_file):
    df = load_swc_as_dataframe(swc_file)
    assert not df["id"].astype(str).str.startswith("#").any()


@pytest.mark.xfail(strict=True, reason=ISSUE_8)
def test_tab_delimited_swc_loads(tmp_path):
    """MorphIO v3.3.3 and other tools emit tab-separated SWC.

    With ``sep=" "`` the whole line lands in the first column and every
    numeric column is NaN -- silently, so the caller gets a dataframe of the
    right shape full of nothing.
    """
    path = tmp_path / "tabs.swc"
    path.write_text(SPACE_DELIMITED.replace(" ", "\t").replace("#\tgenerated", "# generated"))

    df = load_swc_as_dataframe(str(path))

    assert df["x"].tolist() == [0.0, 10.0, 20.0, 10.0]
    assert not df["x"].isna().any()


@pytest.mark.xfail(strict=True, reason=ISSUE_8)
def test_column_aligned_swc_loads(tmp_path):
    """Runs of spaces used for alignment are equally common, and equally fatal."""
    path = tmp_path / "aligned.swc"
    path.write_text(
        "1  1   0.0   0.0  0.0  1.0  -1\n"
        "2  3  10.0   0.0  0.0  1.0   1\n"
    )

    df = load_swc_as_dataframe(str(path))

    assert df["x"].tolist() == [0.0, 10.0]
    assert not df["x"].isna().any()


# -- transform_coordinates_to_volume ---------------------------------------


def test_coordinates_are_counted_into_their_voxels():
    coords = np.array([
        [0.0, 0.0, 0.0],
        [5.0, 5.0, 5.0],    # same voxel as the first
        [10.0, 0.0, 0.0],
    ])

    volume = transform_coordinates_to_volume(
        coords, volume_shape=(3, 2, 2), resolution=(10, 10, 10)
    )

    assert volume.shape == (3, 2, 2)
    assert volume[0, 0, 0] == 2
    assert volume[1, 0, 0] == 1
    assert volume.sum() == 3


def test_counts_are_invariant_to_scaling_coordinates_and_resolution_together():
    coords = np.array([[0.0, 0.0, 0.0], [10.0, 10.0, 10.0]])

    at_10 = transform_coordinates_to_volume(coords, (3, 3, 3), (10, 10, 10))
    at_20 = transform_coordinates_to_volume(coords * 2, (3, 3, 3), (20, 20, 20))

    assert np.array_equal(at_10, at_20)


def test_empty_coordinates_give_an_empty_volume():
    volume = transform_coordinates_to_volume(
        np.zeros((0, 3)), volume_shape=(2, 2, 2), resolution=(10, 10, 10)
    )
    assert volume.sum() == 0


# -- transform_swc_to_volume -----------------------------------------------


def test_swc_nodes_are_counted_into_a_volume(swc_file):
    volume = transform_swc_to_volume(
        swc_file, volume_shape=(3, 2, 2), resolution=(10, 10, 10)
    )

    assert volume.sum() == 4
    assert volume[0, 0, 0] == 1  # the soma at the origin
    assert volume[1, 0, 0] == 1
    assert volume[2, 0, 0] == 1
    assert volume[1, 1, 0] == 1


def test_compartments_filter_which_nodes_are_counted(swc_file):
    soma_only = transform_swc_to_volume(
        swc_file, volume_shape=(3, 2, 2), resolution=(10, 10, 10), compartments=[1]
    )
    dendrite_only = transform_swc_to_volume(
        swc_file, volume_shape=(3, 2, 2), resolution=(10, 10, 10), compartments=[3]
    )

    assert soma_only.sum() == 1
    assert dendrite_only.sum() == 3
    assert soma_only[0, 0, 0] == 1
    assert dendrite_only[0, 0, 0] == 0


# -- find_topological_point_coordinates ------------------------------------


def test_branch_and_termination_nodes_are_found():
    """Node 2 has two children, so it branches; 3 and 4 are nobody's parent."""
    df = pd.DataFrame({
        "id": [1, 2, 3, 4],
        "type": [1, 3, 3, 3],
        "x": [0.0, 10.0, 20.0, 10.0],
        "y": [0.0, 0.0, 0.0, 10.0],
        "z": [0.0, 0.0, 0.0, 0.0],
        "r": [1.0, 1.0, 1.0, 1.0],
        "parent_id": [-1, 1, 2, 2],
    })

    coords = find_topological_point_coordinates(df)

    # Branch nodes first, then terminations.
    assert coords.shape == (3, 3)
    assert np.array_equal(coords[0], np.array([10.0, 0.0, 0.0]))       # branch: node 2
    assert {tuple(c) for c in coords[1:]} == {
        (20.0, 0.0, 0.0),   # termination: node 3
        (10.0, 10.0, 0.0),  # termination: node 4
    }


def test_an_unbranched_neurite_has_only_a_termination():
    df = pd.DataFrame({
        "id": [1, 2, 3],
        "type": [1, 3, 3],
        "x": [0.0, 10.0, 20.0],
        "y": [0.0, 0.0, 0.0],
        "z": [0.0, 0.0, 0.0],
        "r": [1.0, 1.0, 1.0],
        "parent_id": [-1, 1, 2],
    })

    coords = find_topological_point_coordinates(df)

    assert coords.shape == (1, 3)
    assert np.array_equal(coords[0], np.array([20.0, 0.0, 0.0]))


def test_topological_points_can_be_transformed_to_a_volume(swc_file):
    """The documented pairing of the two functions."""
    df = load_swc_as_dataframe(swc_file)
    coords = find_topological_point_coordinates(df)

    volume = transform_coordinates_to_volume(coords, (3, 2, 2), (10, 10, 10))

    assert volume.sum() == coords.shape[0]
