"""Morphology loading and coordinate-to-volume transformation.

SWC is whitespace-delimited but writers disagree on which whitespace: the
Allen files use a single space, while MorphIO (v3.3.3 was the version reported
in issue #8) pads its columns so runs of spaces separate the fields. Splitting
on a literal single space silently turns every padded row into NaNs rather
than raising, so the loading tests below check the parsed values, not just the
shape.

``transform_swc_to_volume`` and ``transform_coordinates_to_volume`` default to
the full CCF shape, which allocates a 1320 x 800 x 1140 array. Every call here
passes a small shape explicitly.
"""

import numpy as np
import pandas as pd
import pytest

from ccf_streamlines.morphology import (
    find_topological_point_coordinates,
    load_swc_as_dataframe,
    transform_coordinates_to_volume,
    transform_swc_to_volume,
)

COLUMNS = ["id", "type", "x", "y", "z", "r", "parent_id"]

# The same three nodes, written five ways.
ROWS = [
    (1, 1, 100.0, 200.0, 300.0, 5.0, -1),
    (2, 2, 110.0, 200.0, 300.0, 1.0, 1),
    (3, 3, 100.0, 215.0, 320.0, 1.5, 1),
]

SINGLE_SPACE = "\n".join(" ".join(str(v) for v in row) for row in ROWS) + "\n"

SWC_VARIANTS = {
    "single_space": SINGLE_SPACE,
    "multiple_spaces": (
        "1 1  100.0   200.0 300.0 5.0 -1\n"
        "2  2 110.0 200.0  300.0 1.0 1\n"
        "3 3 100.0  215.0 320.0   1.5 1\n"
    ),
    "tabs": "\n".join("\t".join(str(v) for v in row) for row in ROWS) + "\n",
    "aligned_columns": (
        "1 1 100.0 200.0 300.0 5.0 -1\n"
        "2 2 110.0 200.0 300.0 1.0  1\n"
        "3 3 100.0 215.0 320.0 1.5  1\n"
    ),
    "trailing_whitespace": "".join(
        " ".join(str(v) for v in row) + "   \n" for row in ROWS
    ),
}


@pytest.fixture
def expected_df():
    return pd.DataFrame(ROWS, columns=COLUMNS)


def write_swc(tmp_path, name, text, header=""):
    path = tmp_path / f"{name}.swc"
    path.write_text(header + text)
    return str(path)


@pytest.mark.parametrize("variant", sorted(SWC_VARIANTS))
def test_load_swc_handles_any_whitespace_delimiter(tmp_path, variant, expected_df):
    """Any run of whitespace separates fields, per issue #8."""
    swc_file = write_swc(tmp_path, variant, SWC_VARIANTS[variant])

    df = load_swc_as_dataframe(swc_file)

    pd.testing.assert_frame_equal(df, expected_df)


def test_load_swc_skips_comment_header(tmp_path, expected_df):
    """A ``#`` header - what MorphIO writes - is still dropped."""
    header = "# generated by MorphIO v3.3.3\n# id type x y z r parent\n"
    swc_file = write_swc(
        tmp_path, "commented", SWC_VARIANTS["multiple_spaces"], header=header
    )

    df = load_swc_as_dataframe(swc_file)

    pd.testing.assert_frame_equal(df, expected_df)


def test_load_swc_keeps_integer_columns(tmp_path):
    """The NaN-filling failure mode also floated ``id``/``type``/``parent_id``."""
    swc_file = write_swc(tmp_path, "ints", SWC_VARIANTS["multiple_spaces"])

    df = load_swc_as_dataframe(swc_file)

    for column in ("id", "type", "parent_id"):
        assert df[column].dtype.kind == "i", column
    assert not df.isna().to_numpy().any()


def test_transform_swc_to_volume_matches_across_delimiters(tmp_path):
    """The delimiter must not reach the projected volume."""
    volume_shape = (40, 40, 40)
    resolution = (10, 10, 10)

    volumes = {
        variant: transform_swc_to_volume(
            write_swc(tmp_path, variant, text),
            volume_shape=volume_shape,
            resolution=resolution,
        )
        for variant, text in SWC_VARIANTS.items()
    }

    reference = volumes["single_space"]
    assert reference.sum() == len(ROWS)
    assert reference[10, 20, 30] == 1
    for variant, volume in volumes.items():
        assert np.array_equal(volume, reference), variant


# The four-node neuron the volume and topology tests below share.
SPACE_DELIMITED = (
    "# generated by a reconstruction tool\n"
    "1 1 0.0 0.0 0.0 1.0 -1\n"
    "2 3 10.0 0.0 0.0 1.0 1\n"
    "3 3 20.0 0.0 0.0 1.0 2\n"
    "4 3 10.0 10.0 0.0 1.0 2\n"
)


@pytest.fixture
def swc_file(tmp_path):
    path = tmp_path / "neuron.swc"
    path.write_text(SPACE_DELIMITED)
    return str(path)


# -- transform_coordinates_to_volume ---------------------------------------


def test_coordinates_are_counted_into_their_voxels():
    coords = np.array(
        [
            [0.0, 0.0, 0.0],
            [5.0, 5.0, 5.0],  # same voxel as the first
            [10.0, 0.0, 0.0],
        ]
    )

    volume = transform_coordinates_to_volume(
        coords, volume_shape=(3, 2, 2), resolution=(10, 10, 10)
    )

    assert volume.shape == (3, 2, 2)
    assert volume[0, 0, 0] == 2
    assert volume[1, 0, 0] == 1
    assert volume.sum() == 3


def test_counts_are_invariant_to_scaling_coordinates_and_resolution_together():
    coords = np.array([[0.0, 0.0, 0.0], [10.0, 10.0, 10.0]])

    at_10 = transform_coordinates_to_volume(coords, (3, 3, 3), (10, 10, 10))
    at_20 = transform_coordinates_to_volume(coords * 2, (3, 3, 3), (20, 20, 20))

    assert np.array_equal(at_10, at_20)


def test_empty_coordinates_give_an_empty_volume():
    volume = transform_coordinates_to_volume(
        np.zeros((0, 3)), volume_shape=(2, 2, 2), resolution=(10, 10, 10)
    )
    assert volume.sum() == 0


# -- transform_swc_to_volume -----------------------------------------------


def test_swc_nodes_are_counted_into_a_volume(swc_file):
    volume = transform_swc_to_volume(
        swc_file, volume_shape=(3, 2, 2), resolution=(10, 10, 10)
    )

    assert volume.sum() == 4
    assert volume[0, 0, 0] == 1  # the soma at the origin
    assert volume[1, 0, 0] == 1
    assert volume[2, 0, 0] == 1
    assert volume[1, 1, 0] == 1


def test_compartments_filter_which_nodes_are_counted(swc_file):
    soma_only = transform_swc_to_volume(
        swc_file, volume_shape=(3, 2, 2), resolution=(10, 10, 10), compartments=[1]
    )
    dendrite_only = transform_swc_to_volume(
        swc_file, volume_shape=(3, 2, 2), resolution=(10, 10, 10), compartments=[3]
    )

    assert soma_only.sum() == 1
    assert dendrite_only.sum() == 3
    assert soma_only[0, 0, 0] == 1
    assert dendrite_only[0, 0, 0] == 0


# -- find_topological_point_coordinates ------------------------------------


def test_branch_and_termination_nodes_are_found():
    """Node 2 has two children, so it branches; 3 and 4 are nobody's parent."""
    df = pd.DataFrame(
        {
            "id": [1, 2, 3, 4],
            "type": [1, 3, 3, 3],
            "x": [0.0, 10.0, 20.0, 10.0],
            "y": [0.0, 0.0, 0.0, 10.0],
            "z": [0.0, 0.0, 0.0, 0.0],
            "r": [1.0, 1.0, 1.0, 1.0],
            "parent_id": [-1, 1, 2, 2],
        }
    )

    coords = find_topological_point_coordinates(df)

    # Branch nodes first, then terminations.
    assert coords.shape == (3, 3)
    assert np.array_equal(coords[0], np.array([10.0, 0.0, 0.0]))  # branch: node 2
    assert {tuple(c) for c in coords[1:]} == {
        (20.0, 0.0, 0.0),  # termination: node 3
        (10.0, 10.0, 0.0),  # termination: node 4
    }


def test_an_unbranched_neurite_has_only_a_termination():
    df = pd.DataFrame(
        {
            "id": [1, 2, 3],
            "type": [1, 3, 3],
            "x": [0.0, 10.0, 20.0],
            "y": [0.0, 0.0, 0.0],
            "z": [0.0, 0.0, 0.0],
            "r": [1.0, 1.0, 1.0],
            "parent_id": [-1, 1, 2],
        }
    )

    coords = find_topological_point_coordinates(df)

    assert coords.shape == (1, 3)
    assert np.array_equal(coords[0], np.array([20.0, 0.0, 0.0]))


def test_topological_points_can_be_transformed_to_a_volume(swc_file):
    """The documented pairing of the two functions."""
    df = load_swc_as_dataframe(swc_file)
    coords = find_topological_point_coordinates(df)

    volume = transform_coordinates_to_volume(coords, (3, 2, 2), (10, 10, 10))

    assert volume.sum() == coords.shape[0]
